### ISSUE TITLE
neopixels not works if lto is not enable

### ISSUE THREAD

**Issue by LuckyTurtleDev** [LuckyTurtleDev/pybadge-high#10]
If one of the following keys is not present at the workspace root `Cargo.toml` the neopixel leds does not work.
```toml
[profile.release]
codegen-units = 1 # better optimizations
lto = true # better optimizations
```
I have no idea why this happens, but I should at least mention it at the doc/example/readme.
